---
- name: Generate inventory file on bastion
  hosts: localhost
  vars:
    guid: dummyavlue
    default_inventory_file: /etc/ansible/hosts
  tasks:
    - name: Copy inventory file from source
      copy:
        src: "{{playbook_dir}}/ansible_inventory"
        dest: "{{default_inventory_file}}"
    - name: Get GUID from host name
      shell: hostname|awk -F. '{print $2}'
      register: guid_output
    - name: Set GUID variable
      set_fact:
        guid: "{{guid_output.stdout}}"
    - name: Replace GUID in ansible inventory
      replace:
        path: "{{default_inventory_file}}"
        regexp: 'PLACEHOLDER_GUID'
        replace: "{{guid}}"

- name: Validate Docker configuration on nodes
  hosts: nodes
  tasks:
    - name: Install Docker if necessary
      package:
        name: docker
        state: present
    - name: Start Docker service if necessary
      service:
        name: docker
        state: started

- name: Configure LDAP authentication
  hosts: localhost
  vars:
    tempfilepath: dummyvalue
    default_inventory_file: /etc/ansible/hosts
  tasks:
    - name: Create temporary file to hold certificate
      tempfile:
        state: file
      register: tempfile_output
    - name: Set temporary file path variable
      set_fact:
        tempfilepath: "{{tempfile_output.path}}"
    - name: Download CA certificate
      get_url:
        url: http://ipa.shared.example.opentlc.com/ipa/config/ca.crt
        dest: "{{tempfilepath}}"
        force: yes
    - name: Replace CA certificate path in ansible inventory
      replace:
        path: "{{default_inventory_file}}"
        regexp: 'PLACEHOLDER_CA_FILEPATH'
        replace: "{{tempfilepath}}"

- name: Validate Openshift packages on bastion
  hosts: localhost
  tasks:
    - name: Install Openshift utils package if necessary
      package:
        name: atomic-openshift-utils
        state: present
    - name: Install Openshift clients package if necesary
      package:
        name: atomic-openshift-clients
        state: present

- name: Check Openshift pre-requisites
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

- name: Run Openshift installer
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml