---
- name: Generate inventory file on bastion
  hosts: localhost
  vars:
    guid: dummyvalue
    ldap_ca_path: dummyvalue
    default_inventory_file: /etc/ansible/hosts
  tasks:
    - name: Copy inventory file from source
      copy:
        src: "{{playbook_dir}}/ansible_inventory"
        dest: "{{default_inventory_file}}"
    - name: Get GUID from host name
      shell: hostname|awk -F. '{print $2}'
      register: guid_output
    - name: Set GUID variable
      set_fact:
        guid: "{{guid_output.stdout}}"
    - name: Replace GUID in ansible inventory
      replace:
        path: "{{default_inventory_file}}"
        regexp: 'PLACEHOLDER_GUID'
        replace: "{{guid}}"
    - name: Create temporary file to hold LDAP certificate
      tempfile:
        state: file
      register: tempfile_output
    - name: Set LDAP CA file path variable
      set_fact:
        ldap_ca_path: "{{tempfile_output.path}}"
    - name: Download CA certificate
      get_url:
        url: http://ipa.shared.example.opentlc.com/ipa/config/ca.crt
        dest: "{{ldap_ca_path}}"
        force: yes
    - name: Replace CA certificate path in ansible inventory
      replace:
        path: "{{default_inventory_file}}"
        regexp: 'PLACEHOLDER_CA_FILEPATH'
        replace: "{{ldap_ca_path}}"
    - name: Reload inventory file to capture updates
      meta: refresh_inventory

- name: Validate Docker configuration on nodes
  hosts: nodes
  tasks:
    - name: Install Docker if necessary
      package:
        name: docker
        state: present
    - name: Start Docker service if necessary
      service:
        name: docker
        state: started

- name: Validate OpenShift packages on bastion
  hosts: localhost
  tasks:
    - name: Install OpenShift utils package if necessary
      package:
        name: atomic-openshift-utils
        state: present
    - name: Install OpenShift clients package if necesary
      package:
        name: atomic-openshift-clients
        state: present

#- name: Check OpenShift pre-requisites
#  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

#- name: Run OpenShift installer
#  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: Copy .kube directory from master to bastion
  hosts: masters[0]
  tasks:
    - name: Copy .kube directory
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: yes

- name: Validate OSE admin login
  hosts: localhost
  tasks:
    - name: Validate that oc admin command returns systemadmin
      shell: oc whoami | grep system:admin

- name: Create PVs on NFS server
  hosts: nfs
  tasks:
    - name: Create PVs
      script: "{{playbook_dir}}/scripts/create_pvs.sh"
    - name: Restart NFS service
      service:
          name: nfs-server
          state: restarted

- name: Create PVs on OSE
  hosts: localhost
  tasks:
    - name: Create PV definition files
      script: "{{playbook_dir}}/scripts/create_pv_definitions.sh"
    - name: Create PVs
      shell: cat /root/pvs/* | oc create -f -

- name: Fix NFS persistent volume recycling
  hosts: localhost
  tasks:
    - name: Pull latest container image
      shell: docker pull registry.access.redhat.com/openshift3/ose-recycler:latest
    - name: Tag latest container image
      shell: docker tag registry.access.redhat.com/openshift3/ose-recycler:latest registry.access.redhat.com/openshift3/ose-recycler:v3.9.30

- name: Smoke test
  hosts: localhost
  tasks:
    - name: Create new project
      shell: oc new-project smoke-test
    - name: Create Node.JS application
      shell: oc new-app nodejs-mongo-persistent